version: '3.8'

name: colorjob
services:
  mysql:                                                  #to use copy of staging db
    image: denisdetkov/manual-testing-db:develop  
    container_name: mysql-container
    networks:
      - colorjob-network

  #mysql:                                                    #to use clear db
    #image: mysql:8.0.36-debian
    #container_name: mysql-container
    #environment:
     # - MYSQL_ROOT_PASSWORD=12211221
      #- MYSQL_DATABASE=colorjob
    #networks:
     # - colorjob-network

  backend:
    image: denisdetkov/manual-testing-colorjob-backend:develop #change to needed branch
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - colorjob-network

  frontend:
    image: denisdetkov/manual-testing-colorjob-frontend:develop #change to needed branch
    container_name: frontend
    environment:
      - SCRIPT_NAME=startDocker
    ports:
       - "4400:4200"
    networks:
      - colorjob-network

networks:
  colorjob-network:
    driver: bridge