const { By } = require('selenium-webdriver');

module.exports = {
    baseHtml: By.css('html'),
    baseErrorClass: By.className('error-message'),
    baseAppCompanies: By.css('app-companies'),
    baseAppProjectsDetails: By.css('app-project-details'),
    baseAppTasks: By.css('app-tasks'),
    baseAppUnits: By.css('app-unit-block'),
    baseNotificationClass: By.className('notification'),
    baseNotificationSuccess: By.className('notification success'),
    baseNotificationError: By.className('notification error'),
    baseBackdropAndModalCss: By.css('.backdrop .modal'),
    baseBackdropManual:By.className('backdrop manual'),
    baseBacksropShowFalse: By.css('.backdrop[show="false"]'),
    baseBackdropFormInvite: By.css('.backdrop .form-invite'),
    baseBackdrop: By.css('.backdrop'),
    baseSaveBtnCss:By.css('btnSave'),
    baseSaveBtn:By.id('btnSave'),
    baseSubmitBtnCss:By.id('btnSubmit'),
    baseBtnCreate: By.id('btnCreate'),
    baseBtnDelete: By.id('btnDelete'),
    baseBtnEdit: By.id('btnEdit'),
    baseBtnInvite: By.id('btnInvite'),
    baseBtnDeleteSelect: By.id('btnDeleteSelect'),
    baseBtnSubmitMobile: By.id('btnSubmitMobile'),
    baseCancelBtn: By.id('btnCancel'),
    baseMainErrorText: By.id('mainErrorText'),
    baseModal: By.className('modal'),
    baseModalTitle: By.className('modal-title'),
    baseDropdownOption: By.className('ng-option'),
    baseNgSelect: By.css('ng-select'),
    baseNgValue:By.css('.ng-value'),
    baseNgValueLable: By.css('.ng-value-label'),
    baseNgValueIcon: By.css('.ng-value-icon'),
    baseNgOptionLable: By.css('.ng-option-label'),
    baseSettingsWrapperBtnEdit: By.css('.settings-wrapper__btn-edit'),
    baseSettingsWrapperHeader: By.css('.settings-wrapper__header'),
    baseTableDetailsTitle: By.css('.table-details__title'),
    baseTableDetailsInfo: By.css('.table-details__info'),
    baseTableDetailsWrapper: By.css('.table-details-wrapper'),
    baseCompanyItem: By.className('company-name'),
    baseAmountItems:By.id('selectAmountItems'),
    baseSelectPaginationText:By.className('total-item-text'),
    baseFilterBtn: By.className('filters-btn'),
    baseFilterForm: By.className('filters-form'),
    baseTitleTableText: By.css('.company-name .ellipsis-text'),
    baseConfirmDelete: By.className('confirm-delete'),
    baseModalNarrow: By.className('modal-narrow'),
    baseDotMenuOpen: By.css('#dotsMenu[editmenuopen]'),
    baseDotsMenuEdit: By.css('#dotsMenu[editmenuopen] #editItem'),
    baseDotMenuDeleteBtn: By.css('#dotsMenu[editmenuopen] #deleteItem'),
    baseDotsActionEditMenuOpen:By.css('.dots-actions[editmenuopen]'),
    baseDotsActions:By.css('.dots-actions'),
    baseProjectNameWrapper: By.css('.project-name__wrapper'),
    baseProjectItem:By.css('.project-item'),
    baselinkProjects: By.id('linkProjects'),
    baseProjectButtonAdminOrEmployee: By.id('linkProjectsAdminOrEmployee'),
    baseDelStatusProjectBtnId: By.id('btnDeleteProject'),
    baseSettingsTabId: By.id('settingsTab'),
    baseAddAreaBtnId: By.id('addAreaField'),
    baseInputErrorStatus: By.css('.form-input-error'),
    baseBtnCloseModal: By.id('btnCloseModal'),
    baseFileInputId: By.id('fileInputMobile'),
    baseRowTasks: By.css('.table-tasks__row'),
    baseDropAreaMobile: By.id('drop-areaMobile'),
    baseSelectItemId:By.id('selectItem'),
    baseFormInvite: By.css('.form-invite'),
    baseDeleteItemId: By.id('deleteItem'),
    baseEditItemId: By.id('editItem'),
    baseFormModalTitle: By.css('.form-modal-title'),
    baseItemInfoList: By.css('.item-info-list'),
    baseUserListSettingsTitle: By.css('.userName-settings-title'),
    baseParagraf: By.css('p'),
    baseInputCreateItem: By.css('.input-create-item'),
    baseBtnFilterCss:By.css('.btn-filters'),
    baseMenuListDotsWrapper: By.css('.menu-list-dots-wrapper'),
    baseEditMenuListOpen: By.css('.editMenuList[editmenuroomopen]'),
    baseNgStarInserted : By.css('.ng-star-inserted'),
    baseCustomStatusBtn: By.css('.customize-status-btn'),
    baseStatusScaleCss: By.css('.view-area-status__item'),
    baseInputElement:By.css('input'),
    baseTableSortIcon: By.css('.table-sort-icon-btn')
}