const { By } = require('selenium-webdriver');

module.exports = {
    areaFormInput: By.css('.area-form-dragIcon-with-input-wrapper .form-input-modal'),
    areaNameInput: By.css('.form-input-modal[placeholder="Area Name"]'),
    areaBoxWithName: By.css('.area-box-with-name-wrapper'),
    areaBoxStatus: By.css('.area-box-status'),
    areaFormRow: By.css('.cdk-drag.area-form-row'),
    areaDeleteAreaBtn: By.id('deleteAreaField'),
    areaCommentsList: By.css('.comments-list__item'),
    areaCommentText: By.css('.comments-list__comment-text p'),
    areaFileItem: By.css('.file-item'),
    areaFileInputId: By.id('fileInputMobile'),
    areaListItem: By.css(`.room-areas-list__item.ng-star-inserted`),
    areaListOfFilesItem: By.css(`.files-container .comments-items>.ng-star-inserted`),
    areaEditor: By.css('.ql-editor.ql-blank'),
    areaSaveCommentBtn: By.css('.btn-save-comment'),
    areaCommentInnerItem: By.css('.comments-list__item--inner'),
    areaMenuListEditCommentOpen: By.id('menuListEditCommentOpen'),
    areaEditMenuList: By.css('.editMenuList[editmenucommentopen]'),
    areaCommentInputDate: By.css('.ql-editor[contenteditable="true"] p'),
    areaFileLink: By.css('a.file-link'),
    areaFileNameTime: By.css('.fileName-with-timeLeft'),
    areaProgressList: By.css('.area-progress-list-areas__item'),
    areaProgressListWithStatus: By.css('.area-progress-list-areas__item[status]'),
    areaModalMini: By.css('.area-modal-mini'),
    areaCommentsWrapper: By.css('.comments-wrapper span'),
    areaFileWrapper: By.css('.files-wrapper span'),
    areaHasComments:By.css('.area-progress-list-areas__item [hascomments="true"]'),
    areaHasAttachment: By.css(`.area-progress-list-areas__item [hasattachments="true"]`),
    areaProgresListStatusToDo: By.css(`.area-progress-list-areas__item[status-name="To Do"]`),
    areaStatusBtn: By.css('.area__status-btn'),
    areaStatusMenuItem: By.css('.area__status-menu__item'),
    areaStatusProgress: By.css('.area-status-progress-list__item'),
    areaBtnConfirm: By.className('btn-confirm'),
    areaDetailsProgress: By.css('.area-details-progress'),
    areaDetailsName: By.css('.area-details-name'),
    areaTopLine: By.css('.top-line'),
    areaTimestamp: By.css('.timestamp'),
    areaChanges: By.css('.changes p'),
    areaMentionList: By.id('quill-mention-list'),
    areaQlFormats: By.css('.ql-formats'),
    areaUserMention: By.id('quill-mention-item-0'),
    areaSpanMention: By.css('span.mention'),
    areaMention: By.css('.mention[data-denotation-char="@"]'),
    areaNameWithMentionUser: By.css('.area-details-way.area-code'),
    areaCheckbox: By.className('checkbox'), 
    areaFileContainerEmpty: By.css('.files-container .no-changes-placeholder.ng-star-inserted '),
    
    templateUpdateTemolate: By.id('updateTemplate'),
    templateName: By.id('templateName'),
    templateDetachBtn: By.className('detach-btn'),

    roomName: By.className('room-name'),
    roomList: By.css('.rooms-list'),
    roomsListItem: By.css('.rooms-list__item'),
    roomsLiListItem: By.css('li .rooms-list__item'),
    roomListRooms: By.css('.rooms-list .room'),
    roomBlock: By.css('app-room-block'),
    roomArrowNameWrapper: By.css('.room-arrow-with-name-wrapper'),
    roomAreasListItem: By.css('.room-areas-list__item'),
    roomProjectProgress: By.css('.project-status-wrapper span'),
    roomAddRoomButton: By.id('addRoom'),
    roomDuplicateFloorRoomVariantsItem: By.css('.duplicate-floor-variants__item.rooms-variants__item'),
    roomEditRoomIcon: By.css('.editRoom-icon'),
    roomAddRoomMenu: By.css('.add-floor-menu.add-room-menu'),
    roomCreateRoomBtn: By.id('createNewRoom'),
    roomNameInput: By.id('roomName'),
    roomAddAreaField: By.id('addAreaField'),
    roomAddFloorMenuCss: By.css('.add-floor-menu'),
    roomDetachBtn: By.css('.detach-btn'),
    roomCheckboxContainer: By.css('.checkbox-container'),
    roomSubtitle :By.id('roomSubtitle'),
    roomNameError:By.id('roomNameError'),
    roomAreasListItemSecond: By.css('li.room-areas-list__item span:nth-of-type(2)'),
    roomAreasList: By.css('.room-areas .ng-star-inserted'),
    roomsListProgressProjectTab: By.css('.room.ng-star-inserted'),
    roomDeleteRoomBtn: By.id('deleteRoomBtn'),
    roomAppRoomBackdrop: By.css('app-room-form app-room-form .backdrop'),
    roomDropList: By.css('.cdk-drop-list.rooms-list'),
    roomArrowLeft: By.css('.room-arrow-icon-wrapper-left'),
    roomArrowRight: By.css('.room-arrow-icon-wrapper-right'),

    floorStatusProgress: By.css('.status-progress-percent'),
    floorAddFloorBtn: By.id('addFloor'),
    florrCreateNewFloorBtn: By.id('createNewFloor'),
    floorCreateFloorInput: By.id('createFloorInput'),
    floorSubmitBtn: By.id('createFloorBtn'),
    floorItem: By.css('.cdk-drag .floor-item'),
    floorMenuListFloorOpen: By.id('menuListFloorOpen'),
    floorDeleteFloorBtn: By.id('deleteFloorBtn'),
    floorAddFloorMenuWithBtnWrapper: By.css('.add-floor-menu-with-btn-wrapper'),
    floorDuplicateFloorVariantsList: By.css('.duplicate-floor-variants-list'),
    floorDuplicateFloorVariantsItem: By.css('.duplicate-floor-variants__item'),
    floorDuplicateFloorsListItem: By.css('.duplicate-units-variants-floors-list__item'),
    duplicateUnitsVariantItem: By.css('.duplicate-units-variants__item'),
    floorEditFloorBtn: By.id('editFloorBtn'),
    floorFormEditFloor: By.css('form.form-edit-floor'),
    floorSaveEditFloorBtn: By.id('saveEditFloorBtn'),
    floorsListItemTitle: By.css('.floors-list__item .floor-cell-name[title]'),
    floorFilterFloors: By.id('filter-floors'),
    floorFiltersListVisible: By.css('.filters-list-wrapper[visible="true"]'),
    floorFiltersListCheckboxContainer: By.css('.filters-list__item .checkbox-container'),
    floorFiltersListHidden: By.css('.filters-list-wrapper[visible="false"]'),
    floorsListDisplayFlex: By.css('.floors-list__item[style*="display: flex;"] .floor-cell-name[title]'),
    floorResetFilterBtn: By.css('#filter-floors .filters-icon.close-icon-forCheck'),
    floorResetFilterAmountFilters: By.css('#filter-floors[amountfilters="0"]'),
    floorActiveItem: By.css('.cdk-drag .floor-item.active'),
    floorItemDrag: By.css('.cdk-drag.floor-item'),
    

    unitNameWrapper: By.css(`.unit-name-wrapper`),
    unitBtnEdit: By.id('editUnitBtn'),
    unitDeleteBtn: By.id('deleteUnitBtn'),
    unitNameWithBtnWrapper: By.css('.unit-name-with-btn-wrapper'),
    unitNameText: By.css('.unit-name-wrapper p'),
    unitBlock: By.css('app-unit-block.cdk-drag.ng-star-inserted'),
    unitNameWrapper: By.css('.unit-name-wrapper'),
    unitDragContainer: By.css('.cdk-drag[cdkdragpreviewcontainer="parent"]'),
    unitCreateUnitForm: By.css('form.form-create-unit-instead-btn'),
    unitUnitForm: By.css('.form-create-unit-instead-btn'),
    unitCreateUnitInput: By.id('createUnitInputDesk'),
    unitCreateNewUnitBtn: By.id('createNewUnit'),
    unitAddUnitBtn: By.id('addUnit'),
    unitCreateUnitSubmitBtn: By.id('createUnitBtnDesk'),
    unitMenuNameWithBtnWrapper: By.id('menuListAddRoomOpen'),
    unitDuplicateUnitsListsWrapper: By.css('.duplicate-units-lists-wrapper'),
    unitDuplicateUnitsVariantsList: By.css('.duplicate-units-variants-list'),
    unitEditMenuList: By.css('.editMenuList'),
    unitCreateUnitInput: By.id('createUnitInputDesk'),
    unitEditUnitInput: By.id('editUnitInput'),
    unitEditUnitBtnSave: By.id('editUnitBtnSave'),
};
