const { By } = require('selenium-webdriver');

module.exports = {

projectCreateProjectButtonId: By.id('btnCreate'),
projectNameMobileId: By.id('projectNameMobile'),
projectCodeId: By.id('projectCode'),
projectNumberMobileId: By.id('projectNumberMobile'),
projectSelectCompanyMobileId: By.id('projectSelectCompanyMobile'),
projectAddressMobileId: By.id('projectAddressMobile'),
projectAddressSecondId: By.id('projectAddressSecond'),
projectSelectStateMobileId: By.id('projectSelectStateMobile'),
projectCityId: By.id('projectCity'),
projectZipCodeId: By.id('projectZipCode'),
projectClientNameMobileId: By.id('projectClientNameMobile'),
projectStartDateId: By.id('projectStartDate'),
projectEndDateId: By.id('projectEndDate'),
projectSubmitButtonMobileId: By.id('btnSubmitMobile'),
projectNameId: By.id('projectName'),
projectNumber: By.css('#projectNumber[forminput="PROJECT_NUMBER"]'),
projectAddressId: By.id('projectAddress'),
projectSelectStateId: By.id('projectSelectState'),
projectSelectCityId: By.id('projectSelectCity'),
projectSubmitButtonId: By.id('btnSubmit'),
projectRow: By.css('.table-projects__row'),
projectStatusWrapper: By.css('.project-status-wrapper .status-bar-colored'),
projectNameWrapper: By.css('.project-name__wrapper .list-name-wrapper'),
projectFilterClientInput: By.css(".filter-field-wrapper [placeholder='Add Client']"),
projectFilterCompanyInput: By.css(".filter-field-wrapper [placeholder='Add Company Name']"),
projectFormBackdrop: By.css('app-project-form .backdrop'),
projectItemInfoList: By.css('.table-projects__row .item-info-list .company-name .list-name-wrapper'),
projectBtnDeleteProjectOpenModalId: By.id('btnDeleteProjectOpenModal'),
projectBtnDeleteProjectId: By.id('btnDeleteProject'),
projectPageHeader: By.xpath("//h1[@class='sub-header__title']"),
}