const { By } = require('selenium-webdriver');
module.exports = {
  userBtnAddUserToProject: By.id('btnAddUsersToProject'),
  userBtnAddUser: By.id('btnAddUsers'),
  userSelectUser: By.id('selectUsers'),
  userInputName: By.id('userName'),
  userInputEmail: By.id('userEmail'),
  userPhoneId: By.id('userPhone'),
  userCompanyId: By.id('userCompany'),
  userRoleId: By.id('userRole'),
  userBtnInviteId: By.id('btnInvite'),
  userRoleDropdown: By.id('userRoleDropdown'),
  userSearchInput: By.id('userSearchInput'),
  userConfirmAddButton: By.id('confirmAddUser'),
  userCancelButton: By.id('cancelAddUser'),
  userNotificationMessage: By.className('notification-message'),
  userCheckboxAcceptTerms: By.name('acceptTerms'),
  userErrorNotification: By.className('error-notification'),
  userTable: By.id('userTable'),
  userTableRow: By.css('.user-table-row'),
  userTableEditButton: By.css('.user-edit-btn'),
  userSelectContainer:By.css('.ng-select-container.ng-has-value'),

  userModalWindow: By.id('userModal'),
  userModalCloseButton: By.css('.modal-close-btn'),
  userModalSaveButton: By.id('modalSaveUser'),
  userLinkUser: By.id('linkUsers'),
  userLinkUserInProject: By.id('linkUsersInProject'),
  userAmountInfo: By.css('.usersAmount-info'),
  userdropdownListBox: By.css('.ng-dropdown-panel[role="listbox"]'),
  userUserEmailMenu: By.css('.user-email'),
  userProfileUserBtn:By.id('profileUserBtn'),
  userProfileLink:By.id('myProfileLink'),
  userBtnChangePasword: By.id('btnChangePassword'),
};
