version: "3.8"
services:
  chrome:
    image: selenium/node-chrome:dev
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./../utils/files:/home/selenium_files
      - shared-downloads:/home/seluser/Downloads
    networks:
      - colorjob-network

  firefox:
    image: selenium/node-firefox:dev
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - colorjob-network

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - colorjob-network

  test-runner:
    image: olevova1983/firsttest:latest
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
      - RUNNING_WITHOUT_VIDEO=true
      - BASE_URL=${BASE_URL}
      - BASE_URL_BACKEND=${BASE_URL_BACKEND}
      - FORCE_ENTITY_CREATION=${FORCE_ENTITY_CREATION}
      - TEST_PATH=${TEST_PATH:-test/**/*.js}
    volumes:
      - shared-downloads:/shared/downloads
    networks:
      - colorjob-network
networks:
  colorjob-network:
    driver: bridge
volumes:
  shared-downloads: