const { nanoid } = require('nanoid');
const baseUrl = process.env.BASE_URL || 'https://dev-frontend.colorjob.terenbro.com';
const baseUrlBackend = process.env.BASE_URL_BACKEND || 'https://dev-backend.colorjob.terenbro.com';
// const baseUrlBackend = 'http://localhost:8080'
// const baseUrl = 'http://localhost:4400'
module.exports = {
    baseUrl,
    baseUrlBackend,
    baseUrlDev: 'https://dev-frontend.colorjob.terenbro.com',
    // URLs for Auto tests
    urlLoginPage: `${baseUrl}/login`,
    urlhomePageForCheck: `${baseUrl}/system/dashboard`,
    mainCompanyPage: `${baseUrl}/system/company`,
    projectsPage: `${baseUrl}/system/projects`,
    companiesPage: `${baseUrl}/system/companies`,
    forgotPasswordUrl: `${baseUrl}/forgot-password`,
    usersPage: `${baseUrl}/system/users`,
    emailForTest: 'justtesting.den@gmail.com',
    emailUseForTest: 'volodymyr_o@terenbro.com',
    emailUseForTestCA: 'volodymyrCA@terenbro.com',
    wrongEmailFormat:'error@',
    matchUrl: `${baseUrl}/system/company`,
    // SA,CA,PM,SU credentials
    email: 'superadmin@gmail.com',
    password: 'colorjob',
    // emailCA:'olevova1983@gmail.com',
    emailCA:'Oleksiyukvolodymyr+ca@gmail.com',
    passwordCA:baseUrl !=='https://dev-frontend.colorjob.terenbro.com' ? 'colorjob' : 'colorjob',
    emailPM:'Oleksiyukvolodymyr+pm@gmail.com',
    passwordPM:baseUrl !=='https://dev-frontend.colorjob.terenbro.com' ? 'colorjob' : 'colorjob',
    // emailSU: 'olevova@ukr.net',
    emailSU: 'Oleksiyukvolodymyr+su@gmail.com',
    passwordSU:baseUrl !=='https://dev-frontend.colorjob.terenbro.com' ? 'colorjob' :  'colorjob',
    emailSUSecond: 'towawo4814@foraro.com',
    inviteUserEmailSU: 'invitePM@gmail.com',
    inviteUserEmail:'serigof730@cetnob.com',
    inviteUserNewEmail: 'pekaw54044@asaud.com',
    inviteUserName: 'Invite',
    inviteUserNameEdit: 'Edit',
    inviteUserPhone: 7778876555,
    taskTestUser:'task-test',
    taskTestUserEmail:'testtask@gmail.com',
    taskTestUserCA: 'CA_parallel',
    taskTestUserPM: 'PM_parallel',
    taskTestUserSU: 'SU_parallel',
    //company name for test
    companyName: 'AT2024',
    companyCheckPlane: 'Check-plane',
    //main test project
    projectNameMain: 'ColorjobAT',
    projectDone: 'DONE',
    projectNameEdit: 'unitEdit',
    projectNameForCA: 'CA test',
    projectNameForPM: 'PM test',
    projectNameForSU: 'SU test',
    projectStatus: 'ProjectDoneStatus',
    projectIDForPM: 'PR-PMPR',
    // Create Company
    newCompanyStreet: 'test2',
    newCompanyApp: '15',
    newCompanyZip: '00000',
    newCompanyPhone: '+1111112111',
    newCompanyEmail: 'fortest@test.com',
    newCompanyEmailTest: 'testtest@test.com',
    newCompanyPlan: 'Enterprise',
    newCompanyCustomPlan: 'Custom',
    newCompanyTeamPlan:'Team',
    newCompanyType: 'Electrical',
    newCompanyTypeFlooring: 'Flooring',
    newCompanyState: 'New York',
    newCompanyCity: 'New York',
    // create project items optional
    newProjectStreet: "street",
    newProjectApp:"without",
    newProjectState:'New York',
    newCompanProjectCity:'New York',
    newProjectClientName: 'Auto Test',
    newProjectZip: '02200',
    startDate:'12.12.23',
    eneDate:'12.12.25',    
    // projects tabs
    view:'view',
    projectProgress:'Project Progress',
    users:'Users',
    tasks:'Tasks',
    activity: 'Activity',
    settings: 'Settings',
    materials: 'Materials',
    // users
    userCAName:'Vova CA test1',
    userSUName:'Vova employee test',
    userSUNameEdit: 'Vova employee edit',
    userPMName: 'Vova PM test',
    userPMNameEdit: 'Vova PM edit',
    //tasks Status
    toDo:'To do',
    inProgress: 'In Progress',
    done:'Done',
    //tasks weight
    huge:'huge',
    medium:'medium',
    // users Role type
    projManager: 'Project Manager',
    standartUser: 'Standard User',
    companyUser: 'Company Admin',
    // dashbord tabs
    projects: 'Projects',
    dashboardTables:{
      company:'cm',
      project:'pj',
      task:'ts'
    },
    //custom status
    statusForEdit: 'color',
    //class locators
    locatorUserNames:'company-name',
    locatorTaskName:'task-name',
    locatorProjects:'table-projects__row',
    // css locator
    locatorProjectsLinkCss:'#linkProjectsAdminOrEmployee',
    locatorProjectFormCss:'app-project-form',
    locatorProjectsCss:'.table-projects__row',
    locatorProjectClientNameCss: '.project-name__wrapper',
    locatorProjectNameInListCss:'.project-name__wrapper',
    locatorListOfProjectInProfileCss: '.table-details__project-row',
    locatorProjectTitleCss:'.table-details-projectName',
    locatorViewProjectBtnUserMenuCss:'#viewProject',
    locatorProjectHeaderTitleCss: '.sub-header__title span',
    locatorDeleteProjectCss: '#btnDeleteProjectOpenModal',
    locatorProjectCloseFormCss: '#btnCloseMobile',
    locatorProjectCancelFormCss: '#btnCancelMobile',
    locatorProjectEditBtnCss:'.settings-wrapper__btn-edit',
    locatorProjectsListCss:'.list-name-wrapper',
    locatorCompaniesLinkCss:'#linkCompanies',
    locatorCompaniesNameCss: '.company-name .ellipsis-text',
    locatorCompanyListCss: '.company-id',
    locatorCompanyFormCss:'app-company-form .backdrop .form-invite.form-create',
    localCompanySettingsCss: '#linkCompanySettings',
    locatorUserNumberCss:'#companyPlanMaxNumberUsers',
    locatorCompaniesListCss: '.table-title-wrapper',
    locatorTasksElementsCss: '.item-info-list',
    locatorCustomMenuBtnCss: '.customize-status-btn',
    locatorAddFloorBtnCss: '.add-floor-menu-with-btn-wrapper',
    locatorAddUnitBtnCss: '#addUnit',
    locatorAddRoomBtnCss: '#addRoom',
    locatorCreateRoomBtnCss: '.add-floor-menu #createNewRoom',
    locatorThreeDotsRoomMenuCss:'.room-name .menu-list-dots-wrapper',
    locatotDeleteUserOpenModalCss: '#deleteUserOpenModal',
    locatorDeletePoUpBtnCss:'#btnDelete',
    locatorSelectDeleteBtnCss:'#btnDeleteSelect',
    locatorSelectDeleteBtnTask:'#btnDeleteTask',
    locatorClosePoUpBtnCss:'#btnClose',
    locatorCancelPoUpBtnCss:'#btnCancel',
    locatorCreatePouUpBtnCss: '#btnCreate',
    locatorDeleteUserCss:'#deleteUserOpenModal',
    locatorEditUserCss:'#btnEdit',
    locatorBackdropCss:'.backdrop',
    locatorModalWindowCss:'.backdrop .modal',
    locatorInviteUserWindowCss:'.backdrop .form-invite',
    locatorHideCompliteBtnCss: '.hide-completed-btn',
    linkSubmitBtnCss: '#btn-submit',
    locatorCancelLinkLoginCss:'#linkCancel',
    locatorAreaTabsCss: '.area-details-tabs-list__link',
    locarorUploadFileErrorCss: '#uploadFileErrordrop-area',
    locatorUploadFileAreaErrorCss: '#uploadFileErrorDropArea',
    locatorTaskNameCss: '.task-name',
    locatorTaskWraperCss: '.task-name__wrapper',
    locatorRoomCss:'.room',
    locatorMaterialsName:'.material-name',
    locatorMaterialsNameClass:'material-name',
    locatorSmallErrorEl: '.small-error-text-field',
    loccatorEditBtn: '#editItem',
    locatorFilterIcon: '.filters-icon.close-icon-forCheck',
    locatorCleraSearching: '.clear-icon',
    locatorMaterialsSupplier: '.material-supplier',
    locatorTableSortIcon: '.table-sort-icon-btn',
    locatorCreateMaterialStatusBtn: '#createUnitBtnDesk',
    locatorDotsMenuId: "#dotsMenu",
    locatorMaterialIdCss: '.material-id',
    //taske createion
    taskDescription:'Test description',
    taskDate: '15.12.25',
    attachmentFilePhoto: 'JavaScript.png',
    attachmentFileVideo: 'video.MP4',
    attachmentFileDoc: 'doc.pdf',
    attachmentFileZip:'doc.zip',
  //View tab create items
    templateBedroom1: 'Bedroom 1',
    newFloorName : 'TestFloor',
    newUnitName : 'TestUnit',
    newRoomName : 'TestUnique',
    newAreaName : 'TestArea',
    newSubtitle : 'Test',
    editRoom : 'Testedit',
    editArea : 'edit',
    template : 'Testtemplate',
    roomBasedOnTemplate : 'roomBasedOnTemplate',
    detuchRoom : 'TestDetuch',
    editFloorName:'test2',
    newTaskName:'FortestTaskRl',
    newTaskNameForUpdate:'TestEditRl2',
    // Materials date
    tagMT:'test tag',
    tagMTFull:'test full',
    supplier:'CA',
    supplierPM:'PM',
    areaMT:'room',
    unit:{
      NOUNIT:'No Unit',
      SF:"SF",
      PCS:'PCS'
    },
    SubmittalStatus:{
      Rejected:'Rejected',
      SamplesOrdered:'Samples Ordered',
      Submitted:'Submitted',
      ApprovedAsNoted:'Approved As Noted',
      Approved:'Approved'
    },
    OrderStatus:{
      NotOrdered:'Not Ordered',
      POSubmitted:'PO Submitted',
      PartiallyOrdered:'Partially Ordered',
      Ordered:'Ordered',
      Arrived:'Arrived'
    },
    materialsPaymentNoStatus: 'No Status',
    materialPaymentStatus:'longpaymentwith',
    materialPaymentStatusPaid:'Paid',
    materialsLocation: 'No Location',
    materialsNot: 'Notes',
    OrderDateMaterials:Date.now(),
    // random date
    randomDate:nanoid(6),
    randomDateFunc: ()=>nanoid(6),
    // files path
    lambdaPathWindows:'C:\\Users\\ltuser\\Downloads\\',
    lambdaPathDockerChrom:'/home/selenium_files/',
    dockerPathForDownloaddFiles: '/shared/downloads',
    //errors
    filesAttachments: 'Error: Unable to upload. The number of files must not exceed 4.'
  };